name: publish to nuget
'on':
  push:
    branches:
      - development
jobs:
  publish:
    name: 'build, pack & publish'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release /p:Version=0.1.3 --output .

      - name: Push
        run: dotnet nuget push CycleTLS.0.1.3.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${NUGET_API_KEY}
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}