name: publish to nuget
'on':
  push:
    branches:
      - development
jobs:
  publish:
    name: 'build, pack & publish'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/CycleTLS/CycleTLS.csproj
          VERSION_STATIC: 0.1.3
          NUGET_KEY: '${{secrets.NUGET_API_KEY}}'